from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import ImageReader
from reportlab.lib.units import inch
from reportlab.lib import colors

from pathlib import Path
from datetime import datetime
import tempfile

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


# ---------- Chart helpers ----------
def _save_histogram(series, out_path: Path, title: str):
    plt.figure()
    series.dropna().plot(kind="hist", bins=20)
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close()


def _save_top_values_bar(series, out_path: Path, title: str):
    s = series.dropna().astype(str)
    vc = s.value_counts().head(8)
    plt.figure()
    vc.plot(kind="bar")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close()


# ---------- PDF helpers ----------
def _draw_cover(c: canvas.Canvas, filename: str, rows: int, cols: int):
    width, height = letter

    # Background header band
    c.setFillColor(colors.HexColor("#0f172a"))
    c.rect(0, height - 170, width, 170, fill=1, stroke=0)

    # Logo + Title
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 26)
    c.drawString(50, height - 80, "BAD")

    c.setFont("Helvetica", 14)
    c.drawString(50, height - 105, "Basic Analysis of Data")

    # Card area
    c.setFillColor(colors.HexColor("#f1f5f9"))
    c.roundRect(50, height - 360, width - 100, 160, 14, fill=1, stroke=0)

    c.setFillColor(colors.HexColor("#0f172a"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(70, height - 235, "Report Summary")

    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#334155"))
    c.drawString(70, height - 260, f"File: {filename}")
    c.drawString(70, height - 280, f"Rows: {rows}")
    c.drawString(70, height - 300, f"Columns: {cols}")
    c.drawString(70, height - 320, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Footer note
    c.setFillColor(colors.HexColor("#64748b"))
    c.setFont("Helvetica", 9)
    c.drawString(50, 50, "Generated by BAD — Basic Analysis of Data (React + FastAPI)")

    c.showPage()


def _draw_column_summary(c: canvas.Canvas, insights):
    width, height = letter
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 50, "Column Summary")

    # Table header
    y = height - 85
    c.setFillColor(colors.HexColor("#0f172a"))
    c.roundRect(50, y, width - 100, 22, 6, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(60, y + 7, "Column")
    c.drawString(260, y + 7, "Kind")
    c.drawString(330, y + 7, "Dtype")
    c.drawString(440, y + 7, "Missing")

    y -= 18
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#0f172a"))

    for col in insights:
        if y < 80:
            c.showPage()
            c.setFont("Helvetica-Bold", 14)
            c.drawString(50, height - 50, "Column Summary (cont.)")
            y = height - 85

        col_name = str(col.get("column", ""))[:24]
        kind = str(col.get("kind", ""))[:10]
        dtype = str(col.get("dtype", col.get("type", "")))[:16]
        missing = str(col.get("missing", 0))

        # Row background alternating
        if (int((height - y) / 14) % 2) == 0:
            c.setFillColor(colors.HexColor("#f8fafc"))
            c.rect(50, y - 4, width - 100, 14, fill=1, stroke=0)
            c.setFillColor(colors.HexColor("#0f172a"))

        c.drawString(60, y, col_name)
        c.drawString(260, y, kind)
        c.drawString(330, y, dtype)
        c.drawString(440, y, missing)
        y -= 14

    c.showPage()


def _draw_charts(c: canvas.Canvas, df, insights):
    width, height = letter
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 50, "Charts")

    y = height - 80

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)
        charts_made = 0

        for col in insights:
            col_name = col.get("column")
            kind = col.get("kind")
            if not col_name or col_name not in df.columns:
                continue

            img_path = tmpdir / f"chart_{charts_made}.png"

            try:
                if kind == "numeric":
                    _save_histogram(df[col_name], img_path, f"{col_name} (Histogram)")
                else:
                    _save_top_values_bar(df[col_name], img_path, f"{col_name} (Top Values)")
            except Exception:
                continue

            try:
                img = ImageReader(str(img_path))
                img_w = 6.5 * inch
                img_h = 3.5 * inch

                if y - img_h < 60:
                    c.showPage()
                    c.setFont("Helvetica-Bold", 14)
                    c.drawString(50, height - 50, "Charts (cont.)")
                    y = height - 80

                c.drawImage(img, 50, y - img_h, width=img_w, height=img_h, preserveAspectRatio=True, mask="auto")
                y -= (img_h + 22)
                charts_made += 1

                # keep PDF size reasonable
                if charts_made >= 8:
                    break
            except Exception:
                continue

    c.showPage()


# ---------- Main API entry ----------
def build_pdf_report(df, insights, meta, path):
    c = canvas.Canvas(str(path), pagesize=letter)

    filename = meta.get("filename", "uploaded file")
    _draw_cover(c, filename, int(df.shape[0]), int(df.shape[1]))
    _draw_column_summary(c, insights)
    _draw_charts(c, df, insights)

    c.save()


# ✅ Compatibility wrapper expected by main.py
def generate_pdf_report(df, insights, path, meta=None):
    if meta is None:
        meta = {"filename": "uploaded file"}
    return build_pdf_report(df, insights, meta, path)
